package eu.rekawek.coffeegb.core.experimental.apu;

/**
 * Detached frame-sequencer control cone derived from the DMG-CPU-B APU clock gates.
 *
 * <p>On the normal netlist path AJER is a toggle DFF, COKE is its inverse, and BARA samples the
 * divider's 512 Hz node on COKE's rising edge. A BARA rising edge clocks the CARU/BYLU ripple:
 * the buffered netlist outputs reduce to HORU={@code !BARA}, BUFY={@code CARU.q}, and
 * BYFE/CATE={@code BYLU.q}. A third channel-local ripple phase distinguishes the two otherwise
 * identical CARU=0/BYLU=0 phases and produces the 64 Hz envelope clock.
 *
 * <p>The island operates once per 4.194304 MHz master T-cycle. CGB speed is an external wiring
 * profile: double speed advances the CPU divider twice and selects bit 13 instead of bit 12. The
 * DMG schematic itself cannot make that CGB choice.
 */
final class ApuClockSignalIsland {

    static final int LENGTH_PULSE = 1;

    static final int SWEEP_PULSE = 1 << 1;

    static final int ENVELOPE_PULSE = 1 << 2;

    /** CGB's divider-tap mux is outside the available DMG topology. */
    static final int EXTERNAL_CGB_DOUBLE_SPEED_TAP = 1;

    /** Sound's later-CGB boot-only +2 divider offset is calibrated profile state. */
    static final int EXTERNAL_CGB_BOOT_DIV_OFFSET = 1 << 1;

    /** Sound's pre/post-CPU commit phase after a speed switch is scheduler/profile state. */
    static final int EXTERNAL_CGB_SPEED_SWITCH_COMMIT_PHASE = 1 << 2;

    /** FrameSequencer's final-four-clock NR52 adjustment is not generated by this gate cone. */
    static final int EXTERNAL_NR52_LATE_WRITE_ADAPTER = 1 << 3;

    /** FrameSequencer's powered-high first-edge suppression is not generated by this gate cone. */
    static final int EXTERNAL_POWER_ON_HIGH_TAP_SUPPRESSION = 1 << 4;

    enum Profile {
        DMG(1, 12,
                EXTERNAL_NR52_LATE_WRITE_ADAPTER
                        | EXTERNAL_POWER_ON_HIGH_TAP_SUPPRESSION),
        CGB_NORMAL(1, 12,
                EXTERNAL_CGB_BOOT_DIV_OFFSET
                        | EXTERNAL_CGB_SPEED_SWITCH_COMMIT_PHASE
                        | EXTERNAL_NR52_LATE_WRITE_ADAPTER
                        | EXTERNAL_POWER_ON_HIGH_TAP_SUPPRESSION),
        CGB_DOUBLE(2, 13,
                EXTERNAL_CGB_DOUBLE_SPEED_TAP
                        | EXTERNAL_CGB_BOOT_DIV_OFFSET
                        | EXTERNAL_CGB_SPEED_SWITCH_COMMIT_PHASE
                        | EXTERNAL_NR52_LATE_WRITE_ADAPTER
                        | EXTERNAL_POWER_ON_HIGH_TAP_SUPPRESSION);

        private final int dividerIncrement;

        private final int tapBit;

        private final int externalRules;

        Profile(int dividerIncrement, int tapBit, int externalRules) {
            this.dividerIncrement = dividerIncrement;
            this.tapBit = tapBit;
            this.externalRules = externalRules;
        }

        int dividerIncrement() {
            return dividerIncrement;
        }

        int tapBit() {
            return tapBit;
        }

        boolean doubleSpeed() {
            return dividerIncrement == 2;
        }

        int externalRules() {
            return externalRules;
        }
    }

    private static final int COMMITTED = 0;

    private static final int DRIVEN = 1;

    private static final int RESOLVED = 2;

    private final Profile profile;

    private int div;

    private int nextDiv;

    /** AJER.q; its inverse COKE clocks BARA. */
    private boolean ajer;

    private boolean nextAjer;

    /** BARA.q, the sampled selected-divider node. */
    private boolean bara;

    private boolean nextBara;

    /** CARU.q, exposed through BUFY_256Hz on the normal test mux path. */
    private boolean caru;

    private boolean nextCaru;

    /** BYLU.q, exposed through BYFE_128Hz and CATE_128Hz. */
    private boolean bylu;

    private boolean nextBylu;

    /** Channel-local final divide phase needed to distinguish step 3 from step 7. */
    private boolean envelopeHighHalf = true;

    private boolean nextEnvelopeHighHalf = true;

    private int nextStep;

    private int step;

    private int pulses;

    private int firedStep = -1;

    private boolean powered;

    private boolean divResetDrive;

    private int phase;

    ApuClockSignalIsland(Profile profile, int initialDiv, boolean powered) {
        if (profile == null) {
            throw new NullPointerException("profile");
        }
        this.profile = profile;
        this.div = initialDiv & 0xffff;
        this.nextDiv = div;
        this.powered = powered;
    }

    void setPowered(boolean powered) {
        require(COMMITTED, "setPowered");
        this.powered = powered;
    }

    /** DRIVE: presents either the next free-running divider value or FF04's clear value. */
    void drive(boolean divReset) {
        require(COMMITTED, "drive");
        divResetDrive = divReset;
        nextDiv = divReset ? 0 : (div + profile.dividerIncrement()) & 0xffff;
        phase = DRIVEN;
    }

    /** RESOLVE: settles AJER/COKE, BARA, the ripple latches, and decoded pulse wires. */
    void resolve() {
        require(DRIVEN, "resolve");
        pulses = 0;
        firedStep = -1;
        nextStep = step;

        if (!powered) {
            // APU_RESET holds the clock divider cells low. The final envelope phase is chosen so
            // the first complete BARA cycle after release decodes as frame-sequencer step zero.
            nextAjer = false;
            nextBara = false;
            nextCaru = false;
            nextBylu = false;
            nextEnvelopeHighHalf = true;
            nextStep = 0;
            phase = RESOLVED;
            return;
        }

        nextAjer = !ajer;
        boolean cokeRising = ajer && !nextAjer;
        nextBara = cokeRising ? selectedTap(nextDiv) : bara;
        nextCaru = caru;
        nextBylu = bylu;
        nextEnvelopeHighHalf = envelopeHighHalf;

        if (!bara && nextBara) {
            // BARA.q rises. CARU toggles; CARU.~q's rising edge then toggles BYLU. The third
            // phase toggles on the other CARU rising edge for the 8-step envelope cadence.
            nextCaru = !caru;
            if (caru && !nextCaru) {
                nextBylu = !bylu;
            } else if (!caru && nextCaru && !bylu) {
                nextEnvelopeHighHalf = !envelopeHighHalf;
            }
        }

        if (bara && !nextBara) {
            firedStep = step;
            if (nextCaru) {
                pulses |= LENGTH_PULSE;
            }
            if (nextCaru && nextBylu) {
                pulses |= SWEEP_PULSE;
            }
            if (!nextCaru && !nextBylu && nextEnvelopeHighHalf) {
                pulses |= ENVELOPE_PULSE;
            }
            nextStep = (step + 1) & 7;
        }
        phase = RESOLVED;
    }

    /** COMMIT: publishes every latch simultaneously. */
    void commit() {
        require(RESOLVED, "commit");
        div = nextDiv;
        ajer = nextAjer;
        bara = nextBara;
        caru = nextCaru;
        bylu = nextBylu;
        envelopeHighHalf = nextEnvelopeHighHalf;
        step = nextStep;
        divResetDrive = false;
        phase = COMMITTED;
    }

    int div() {
        return div;
    }

    int firedStep() {
        require(RESOLVED, "firedStep");
        return firedStep;
    }

    int pulses() {
        require(RESOLVED, "pulses");
        return pulses;
    }

    boolean horu512Hz() {
        return !bara;
    }

    boolean bufy256Hz() {
        return caru;
    }

    boolean byfe128Hz() {
        return bylu;
    }

    boolean cate128Hz() {
        return bylu;
    }

    int nextStep() {
        return step;
    }

    boolean divResetDrive() {
        return divResetDrive;
    }

    private boolean selectedTap(int value) {
        return (value & (1 << profile.tapBit())) != 0;
    }

    private void require(int expected, String operation) {
        if (phase != expected) {
            throw new IllegalStateException(operation + " called outside its signal phase");
        }
    }
}
